version: '3.5'
networks:
  puerto_net:
    name: puerto_net
    ipam:
      config:
        - subnet: 172.20.7.0/24
services:
  ms-base:
    image: aescobaricc/ms-base-api:0.0.1
    container_name: ms-base-api
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      args:
        BRANCH_UTIL_LIB: master
        #BRANCH_UTIL_MODEL: master
    env_file: .env
    volumes:
      - .:/api-run
    ports:
      - "8080:8000"
    networks:
      puerto_net:
        ipv4_address: 172.20.7.3